platform:
- x64


environment:
  matrix:
    - JDK: C:\Program Files (x86)\Java\jdk1.8.0
      JDKNAME: jdk1.8.0
      ARCH: x86
    - JDK: C:\Program Files\Java\jdk1.8.0
      JDKNAME: jdk1.8.0
      ARCH: x64
    - JDK: C:\Program Files\Java\jdk9
      JDKNAME: jdk9
      ARCH: x64
    - JDK: C:\Program Files\Java\jdk10
      JDKNAME: jdk10
      ARCH: x64
    
build_script:
    - call "C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall.bat" %ARCH%
    - cl.exe /EHsc /O2 /GL /GA /Ob2 /nologo /W3 /MT /Zi /wd4800 /wd4305 /wd4244 -I"%JDK%\include" -I"%JDK%\include\win32" -I"J:\dev\dialog\mecab" -c MeCab_wrap.cxx 
    - link.exe /nologo /OPT:REF /OPT:ICF /LTCG /NXCOMPAT /DYNAMICBASE /MACHINE:%ARCH% -out:MeCab.dll J:\dev\dialog\mecab\libmecab.lib MeCab_wrap.obj /dll

after_build:
    - 7z a mecab-java-msvc-%JDKNAME%-%ARCH%.zip %APPVEYOR_BUILD_FOLDER%\MeCab.dll
    - 7z a mecab-java-msvc-%JDKNAME%-%ARCH%.zip %APPVEYOR_BUILD_FOLDER%\org\
    - 7z a mecab-java-msvc-%JDKNAME%-%ARCH%.zip %APPVEYOR_BUILD_FOLDER%\test.java

artifacts: 
  - path: 'mecab-java-msvc-*.zip'
    name: MeCab-Java-MSVC
deploy:
  description: 'MeCab-Java-MSVC'
  provider: GitHub
  auth_token:
    secure: 3dyLxnmyBTMNPbsgWOuwarwBotzIDjkf9y8vs8DoxBhYIVI2IiCDO6pNmuCadgCs
  artifact: MeCab-Java-MSVC    
  draft: false
  prerelease: false
  on:
    appveyor_repo_tag: true
